### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/domodule#1]
modernized fidel + data-attrs....

html:

``` html
<div data-module="Widget" data-module-id="123">
  <input type="text" data-el="textBox"/>
  <button data-action="save"></button>
</div>
```

js:

``` js
class Widget extends Domodule {
   //this is optional 
  constructor(el, options, els) {
   this.super(el, options, els);
   //some stuff here
  }
  actions: {
    save: (el) => {
     const val = this.els.textBox.val();
     const id = this.options.id; //123
    }
  }

}
```
## Features
- on dom ready class automatically gets instantiated for each data-module.
- auto bind actions, els, options from dom
- no jquery needed
- `this.find('.blah')` does a `this.el.querySelector('.blah')`

//cc @dawnerd

**Comment by jgallen23** [comment]
@mturnwall would be interested in your thoughts as well

**Comment by dawnerd** [comment]
what about notifying modules of changes? should Domodule be a kind of event broker?

**Comment by jgallen23** [comment]
@dawnerd what kind of changes?  use case?

**Comment by dawnerd** [comment]
comments module + pagination module. When pagination module is clicked comments should know to refresh. Or if there's a module that depends on user auth state

**Comment by jgallen23** [comment]
we are running into a similar issue with pagedata.  Having modules communicate with eachother.  Maybe a global EventBus or something?  or should `Domodule` have `on()` and `trigger()`?

**Comment by dawnerd** [comment]
I could see it either way, as long as modules can communicate in some fashion. Since we're not using jquery maybe a separate event class that modules register event handlers to?

**Comment by jgallen23** [comment]
I could see API classes and non-dom related things needing events, so maybe its separate

**Comment by jgallen23** [comment]
I bet there is a nice, lightweight, event emitter library that we could just use.
