### ISSUE TITLE
Some way to link external actions?

### ISSUE THREAD

**Issue by dawnerd** [firstandthird/domodule#3]
Say you have a button that is not part of the module but you want it to trigger an action in the module, like opening a modal (where the modal is the module). Would this be something that would be useful to put into Domodule core? Not exactly sure the best way it can be implemented. Maybe something the modules themselves setup like so:

``` js
class Test extends Domodule {
  constructor(el) {
    super(el);
    this.bindExternal('data-action-modal', this.open, 'click');
  }
}
```

**Comment by jgallen23** [comment]
the way I did it before was to create an OpenModal module for the button and then have another modal Module for the specific modal.  In the OpenModal, it discovers new modules when it opens and renders the template.

**Comment by dawnerd** [comment]
Only "problem" with that is now every instance requires a unique id. Maybe if there's no id we randomly generate one?
